version: '3.7'

services:
  store:
    container_name: store
    image: 'store'
    depends_on:
      - db-store
    build:
      context: docker
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-store:5432/db-store
      - SPRING_DATASOURCE_USERNAME=username
      - SPRING_DATASOURCE_PASSWORD=password
    volumes:
      - ./:/var/www/store/
      - m2-repo:/home/root/.m2/repository
    networks:
      - network-store
    ports:
      - "8080:8080"
    entrypoint:
      - /var/www/store/docker/build_and_run.sh

  db-store:
    container_name: db-store
    image: 'postgres:13.1-alpine'
    environment:
      - POSTGRES_DB=db-store
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
    volumes:
      - db-store-volume:/var/lib/postgresql/data
    networks:
      - network-store
    ports:
      - "5432:5432"

volumes:
  db-store-volume:
  m2-repo:

networks:
  network-store: