version: '2'
services:
  store:
    image: 'store'
    build:
      context: .
    container_name: store
    depends_on:
      - store-db
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://store-db:5432/store-db
      - SPRING_DATASOURCE_USERNAME=username
      - SPRING_DATASOURCE_PASSWORD=password
    volumes:
      - ./../../../:/var/www/store/
    networks:
      - store-network

    entrypoint:
      - /var/www/store/watcher.sh

  store-db:
    image: 'postgres:13.1-alpine'
    container_name: store-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=store-db
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
    volumes:
      - store-db:/var/lib/postgresql/data

    networks:
      - store-network

volumes:
  store-db:

networks:
  store-network: